User.create(first_name: 'Ryan', last_name: 'Kwon', email: 'rynkwn@gmail.com', password: 'phoenix')
user = User.create(first_name: 'Foo', last_name: 'Bar', email: 'foo@bar.com', password: 'password')
item = user.items.create(name: 'Item', price: 10, quantity: 10, desc: 'Test item', item_type: 'General', tags: ['Great', 'Useful', 'Cheap'])
item = user.items.create(name: 'Baby Stroller', price: 10, quantity: 10, desc: 'Test item', item_type: 'General', tags: ['Baby', 'Stroller', 'Cheap'])
item = user.items.create(name: 'Baby Food', price: 10, quantity: 10, desc: 'Test item', item_type: 'General', tags: ['Baby', 'Food', 'Healthy'])
item = user.items.create(name: 'Baby Sweater', price: 10, quantity: 10, desc: 'Test item', item_type: 'Clothing', tags: ['Baby', 'Sweater', 'Warm'])
item = user.items.create(name: 'Moisturizing Shampoo', price: 10, quantity: 10, desc: 'Test item', item_type: 'Beauty', tags: ['Skin', 'Healthy', 'Shampoo', 'Moisturizing'])
item = user.items.create(name: 'Clear-Skin Aloe', price: 10, quantity: 10, desc: 'Test item', item_type: 'Beauty', tags: ['Skin', 'Healthy', 'Aloe', 'Clear'])
item = user.items.create(name: 'Marcay Primer', price: 10, quantity: 10, desc: 'Test item', item_type: 'Beauty', tags: ['Marcay', 'Makeup', 'Primer'])
review = item.reviews.build(user_id: user.id, body: 'Alright', rating: 5)
review.save